language: cpp

matrix:
    include:
      - os: linux
        compiler: clang
        addons:
            apt:
                packages:
                    - libgl1-mesa-dev
                    - libxrandr-dev
                    - libxcursor-dev
                    - libxinerama-dev
                    - libxxf86vm-dev
                    - libopus-dev
                    - libenet-dev
                    - libasound-dev
                    - pulseaudio
                    - libtheora-dev
                    - libv4l-dev

      - os: linux
        compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-4.9
                    - libgl1-mesa-dev
                    - libxrandr-dev
                    - libxcursor-dev
                    - libxinerama-dev
                    - libxxf86vm-dev
                    - libopus-dev
                    - libenet-dev
                    - libasound-dev
                    - pulseaudio
                    - libtheora-dev
                    - libv4l-dev
        env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

      - os: linux
        compiler: clang
        addons:
            apt:
                packages:
                    - g++-multilib
                    - libc6-dev-i386
                    - libgl1-mesa-dev:i386
                    - libxrandr-dev:i386
                    - libxcursor-dev:i386
                    - libxinerama-dev:i386
                    - libxxf86vm-dev:i386
                    - libopus-dev:i386
                    - libenet-dev:i386
                    - libasound-dev:i386
                    - pulseaudio:i386
                    - libtheora-dev:i386
                    - libv4l-dev:i386
        env:
            - PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig/
            - MATRIX_EVAL="CFLAGS=-m32 && LIB_CFLAGS=-m32"

      - os: linux
        compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-4.9
                    - g++-multilib
                    - libc6-dev-i386
                    - libgl1-mesa-dev:i386
                    - libxrandr-dev:i386
                    - libxcursor-dev:i386
                    - libxinerama-dev:i386
                    - libxxf86vm-dev:i386
                    - libopus-dev:i386
                    - libenet-dev:i386
                    - libasound-dev:i386
                    - pulseaudio:i386
                    - libtheora-dev:i386
                    - libv4l-dev:i386
        env:
            - PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig/
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && CFLAGS=-m32 && LIB_CFLAGS=-m32"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
    email:
        on_success: never
        on_failure: change
