sudo: required
language: cpp
compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - libglfw-dev
            - libopus-dev
            - libenet-dev
            - libasound-dev

matrix:
    include:
      - os: linux
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-4.9
        env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

      - os: linux
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-5
        env:
            - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

      - os: linux
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-6
        env:
            - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - eval "${MATRIX_EVAL}"
    - mkdir build
    - cd build
    - cmake ..

script: make
