language: cpp

matrix:
    include:
      - os: linux
        compiler: clang
        addons:
            apt:
                packages:
                    - libglfw3-dev
                    - libopus-dev
                    - libenet-dev
                    - libasound-dev

      - os: linux
        compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-4.9
                    - libglfw3-dev
                    - libopus-dev
                    - libenet-dev
                    - libasound-dev
        env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

      - os: linux
        compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-5
                    - libglfw3-dev
                    - libopus-dev
                    - libenet-dev
                    - libasound-dev
        env:
            - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

      - os: linux
        compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-6
                    - libglfw3-dev
                    - libopus-dev
                    - libenet-dev
                    - libasound-dev
        env:
            - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make
