language: cpp

matrix:
    include:
      - os: linux
        compiler: clang
        addons:
            apt:
                packages:
                    - xorg-dev
                    - libopus-dev
                    - libenet-dev
                    - libasound-dev
                    - pulseaudio

      - os: linux
        compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-4.9
                    - xorg-dev
                    - libopus-dev
                    - libenet-dev
                    - libasound-dev
                    - pulseaudio
        env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
    email:
        on_success: never
        on_failure: change
