language: cpp
compiler: gcc

addons:
    apt:
        packages:
            - libglfw-dev
            - libopus-dev
            - libenet-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make
